# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(709, 570)
        MainWindow.setSizeIncrement(QtCore.QSize(1, 1))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.groupBox)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.textExample = QtWidgets.QPlainTextEdit(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textExample.sizePolicy().hasHeightForWidth())
        self.textExample.setSizePolicy(sizePolicy)
        self.textExample.setMinimumSize(QtCore.QSize(200, 0))
        self.textExample.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.textExample.setFont(font)
        self.textExample.setTabChangesFocus(True)
        self.textExample.setPlainText("")
        self.textExample.setObjectName("textExample")
        self.horizontalLayout_5.addWidget(self.textExample)
        self.gridLayout_2.addWidget(self.frame_5, 4, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.groupBox)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.textGrammar = QtWidgets.QPlainTextEdit(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textGrammar.sizePolicy().hasHeightForWidth())
        self.textGrammar.setSizePolicy(sizePolicy)
        self.textGrammar.setMinimumSize(QtCore.QSize(200, 0))
        self.textGrammar.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.textGrammar.setFont(font)
        self.textGrammar.setTabChangesFocus(True)
        self.textGrammar.setPlainText("")
        self.textGrammar.setObjectName("textGrammar")
        self.horizontalLayout_3.addWidget(self.textGrammar)
        self.gridLayout_2.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.textWord = QtWidgets.QPlainTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textWord.sizePolicy().hasHeightForWidth())
        self.textWord.setSizePolicy(sizePolicy)
        self.textWord.setMinimumSize(QtCore.QSize(200, 0))
        self.textWord.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.textWord.setFont(font)
        self.textWord.setTabChangesFocus(True)
        self.textWord.setPlainText("")
        self.textWord.setObjectName("textWord")
        self.horizontalLayout_2.addWidget(self.textWord)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.groupBox)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.textDef = QtWidgets.QPlainTextEdit(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textDef.sizePolicy().hasHeightForWidth())
        self.textDef.setSizePolicy(sizePolicy)
        self.textDef.setMinimumSize(QtCore.QSize(200, 0))
        self.textDef.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.textDef.setFont(font)
        self.textDef.setTabChangesFocus(True)
        self.textDef.setPlainText("")
        self.textDef.setObjectName("textDef")
        self.horizontalLayout_4.addWidget(self.textDef)
        self.gridLayout_2.addWidget(self.frame_4, 3, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem5 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.textPronun = QtWidgets.QPlainTextEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textPronun.sizePolicy().hasHeightForWidth())
        self.textPronun.setSizePolicy(sizePolicy)
        self.textPronun.setMinimumSize(QtCore.QSize(200, 30))
        self.textPronun.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.textPronun.setFont(font)
        self.textPronun.setTabChangesFocus(True)
        self.textPronun.setPlainText("")
        self.textPronun.setObjectName("textPronun")
        self.horizontalLayout.addWidget(self.textPronun)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.groupBox)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnAddDef = QtWidgets.QPushButton(self.frame_6)
        self.btnAddDef.setObjectName("btnAddDef")
        self.horizontalLayout_6.addWidget(self.btnAddDef)
        self.btnAddWord = QtWidgets.QPushButton(self.frame_6)
        self.btnAddWord.setObjectName("btnAddWord")
        self.horizontalLayout_6.addWidget(self.btnAddWord)
        self.btnDelete = QtWidgets.QPushButton(self.frame_6)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_6.addWidget(self.btnDelete)
        self.btnClear = QtWidgets.QPushButton(self.frame_6)
        self.btnClear.setObjectName("btnClear")
        self.horizontalLayout_6.addWidget(self.btnClear)
        self.gridLayout_2.addWidget(self.frame_6, 6, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.groupBox)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.listVocabulary = QtWidgets.QListView(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.listVocabulary.setFont(font)
        self.listVocabulary.setObjectName("listVocabulary")
        self.verticalLayout.addWidget(self.listVocabulary)
        self.btnOutput = QtWidgets.QPushButton(self.frame_7)
        self.btnOutput.setObjectName("btnOutput")
        self.verticalLayout.addWidget(self.btnOutput)
        self.gridLayout_2.addWidget(self.frame_7, 0, 1, 7, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textWord, self.textPronun)
        MainWindow.setTabOrder(self.textPronun, self.textGrammar)
        MainWindow.setTabOrder(self.textGrammar, self.textDef)
        MainWindow.setTabOrder(self.textDef, self.textExample)
        MainWindow.setTabOrder(self.textExample, self.btnAddDef)
        MainWindow.setTabOrder(self.btnAddDef, self.btnAddWord)
        MainWindow.setTabOrder(self.btnAddWord, self.btnDelete)
        MainWindow.setTabOrder(self.btnDelete, self.btnClear)
        MainWindow.setTabOrder(self.btnClear, self.btnOutput)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Vocabulary Generator"))
        self.label_5.setText(_translate("MainWindow", "Example"))
        self.label_3.setText(_translate("MainWindow", "Grammar"))
        self.label.setText(_translate("MainWindow", "Word"))
        self.label_4.setText(_translate("MainWindow", "Definition"))
        self.label_2.setText(_translate("MainWindow", "Pronunciation"))
        self.btnAddDef.setText(_translate("MainWindow", "Add Definition"))
        self.btnAddWord.setText(_translate("MainWindow", "Add Word"))
        self.btnDelete.setText(_translate("MainWindow", "Delete"))
        self.btnClear.setText(_translate("MainWindow", "Clear"))
        self.label_6.setText(_translate("MainWindow", "Vocabulary List"))
        self.btnOutput.setText(_translate("MainWindow", "Output formatted text for Anki"))

